# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

source 'https://github.com/CocoaPods/Specs.git'

target 'reckonMe' do
pod 'DCIntrospect-ARC'
pod 'UIImage+PDF'
pod 'PrettyTimestamp'
pod 'proj4'
end

target 'reckonMeTests' do

end

# copy the acknowledgements to the settings bundle
post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-reckonMe/Pods-reckonMe-acknowledgements.plist', 'Resources/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
