# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

source 'https://github.com/CocoaPods/Specs.git'

target 'reckonMe' do
pod 'DCIntrospect-ARC', '~> 0.0.8'
end

target 'reckonMeTests' do

end

